#!/bin/bash
# necessario instalacao do pacote jq
# necessario instalacao do awscli
# contempla EXT4 e XFS
# uso: comando /dev/device

# Altere os valores de Access Key e Secret Key
export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export AWS_DEFAULT_REGION=us-east-1

# limite de percentual de disco para resize
plimite="85"

# percentual de aumento
pinc="10"

device_path=$1
pdisk=`df $device_path --output=pcent | sed -n 2p | tr -d ' %'`

# comparacao do percentual de uso de disco
if [ $pdisk -gt $plimite ]
then
    sdisk=`df -h $device_path --output=size | sed -n 2p | tr -d ' G'`
    psize=`echo "$sdisk * 0.$pinc / 1" | bc`
    tsize=`echo "$sdisk + $psize" | bc`
    instance_id=`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`
    qtde_devices=`aws ec2 describe-instances --instance-ids $instance_id | jq '.Reservations[].Instances[].BlockDeviceMappings|length'`
    device_sd=`echo $device_path | cut -d '/' -f 3 | tr -d 'xv'`
    device_sd=`echo "s$device_sd"`
    for (( c=0; c<$qtde_devices; c++ ))
    do
        device=`aws ec2 describe-instances --instance-ids $instance_id | jq '.Reservations[].Instances[].BlockDeviceMappings['$c'].DeviceName' | cut -d '/' -f 3 | tr -d '"'`
        volume_id=`aws ec2 describe-instances --instance-ids $instance_id | jq '.Reservations[].Instances[].BlockDeviceMappings['$c'].Ebs.VolumeId' | tr -d '"'`
        if [ "$device_sd" == $device ]
        then
            aws ec2 modify-volume --volume-id $volume_id --size $tsize
            sleep 30
            fstype=`df $device_path --output=fstype | sed -n 2p`
            if [ $fstype == 'ext4' ]
            then
                resize2fs $device_path
            fi
            if [ $fstype == 'xfs' ]
            then
                xfs_growfs $device_path
            fi
        fi
    done
fi
